version: '3.3'  # Use the appropriate version

services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/your_database_name

volumes:
  db-data: