default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: docker_example_development

test:
  <<: *default
  database: docker_example_test

production:
  <<: *default
  database: docker_example_production
  username: postgres
  password: postgres
